### ISSUE TITLE
singularity-2.4.3 install fails

### ISSUE THREAD

**Issue by moskalenko** [apptainer/singularity#1362]
## Version of Singularity:

2.4.3

### Expected behavior

make should produce a complete build

make install should be able to run successfully using a successful build produced with 'make' on a different node with root nosquash for the build and install prefix filesystems.

### Actual behavior

Since make install must by run by the root user there should be no build steps at that point. However, running 'make install' as root after a completed build produces the following error:

...
Making install in util
make[2]: Entering directory `/dist/apps/singularity/singularity-2.4.3/src/util'
make[3]: Entering directory `/dist/apps/singularity/singularity-2.4.3/src/util'
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/dist/apps/singularity/singularity-2.4.3/src/util'
make[2]: Leaving directory `/dist/apps/singularity/singularity-2.4.3/src/util'
make[2]: Entering directory `/dist/apps/singularity/singularity-2.4.3/src'
gcc -DHAVE_CONFIG_H -I.  -DBINDIR=\"/apps/singularity/2.4.3/bin\" -DSYSCONFDIR=\"/apps/singularity/2.4.3/etc\" -DLOCALSTATEDIR=\"/apps/singularity/2.4.3/var\" -DLIBEXECDIR=\"/apps/singularity/2.4.3/libexec\" -DNS_CLONE_NEWPID -DNS_CLONE_FS -DNS_CLONE_NEWNS -DNS_CLONE_NEWUSER -DNS_CLONE_NEWIPC -DNS_CLONE_NEWNET -DSINGULARITY_NO_NEW_PRIVS -DSINGULARITY_MS_SLAVE -DSINGULARITY_NO_SETNS -DSINGULARITY_SETNS_SYSCALL  -Wall -fpie -fPIC -g -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -fstack-protector --param ssp-buffer-size=4 -MT docker_extract-docker-extract.o -MD -MP -MF .deps/docker_extract-docker-extract.Tpo -c -o docker_extract-docker-extract.o `test -f 'docker-extract.c' || echo './'`docker-extract.c
docker-extract.c:12:21: error: archive.h: No such file or directory
docker-extract.c:13:27: error: archive_entry.h: No such file or directory
...
make[2]: *** [docker_extract-docker-extract.o] Error 1
make[2]: Leaving directory `/dist/singularity-2.4.3/src'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/dist/singularity-2.4.3/src'
make: *** [install-recursive] Error 1

If libarchive-devel is adding to the install node the install proceeds to completion, but results in the singularity binary being dynamically linked to libarchive.so.2 and not being portable anymore, which wasn't the case with <=2.4.2

### Steps to reproduce behavior

Do a build as a regular user on a build node with libarchive-devel installed

Change to root on a secure node that can write to both the build tree and the install prefix, but doesn't have libarchive-devel and run 'make install'.

This is a new issue in 2.4.3. It wasn't present in 2.4.2.

**Comment by DrDaveD** [comment]
Having dependencies on shared libraries is normal for open source tools, I don't see this as a problem.  Packaging systems are supposed to handle the dependency.  I confirm that it does work with the 2.4.3 rpm packaging.  I haven't tried the debian packaging; can anyone else confirm whether that automatically pulls in the correct libarchive package?  I don't see it listed explicitly in the "Depends", but rpm infers the equivalent "Requires" and I don't know about dpkg.  I think people who install outside of packaging systems are expected to manage dependencies themselves.

**Comment by DrDaveD** [comment]
Having dependencies on shared libraries is normal for open source tools, I don't see this as a problem.  Packaging systems are supposed to handle the dependency.  I confirm that it does work with the 2.4.3 rpm packaging.  I haven't tried the debian packaging; can anyone else confirm whether that automatically pulls in the correct libarchive package?  I don't see it listed explicitly in the "Depends", but rpm infers the equivalent "Requires" and I don't know about dpkg.  I think people who install outside of packaging systems are expected to manage dependencies themselves.

**Comment by DrDaveD** [comment]
So the fact that libarchive.so.2 is missing on a different machine is a non-issue, I think.  That's up to the user to manage.

So the only real problem is that a make install triggers some recompiling even on something that was already built.  I was able to reproduce this issue between two RHEL7 systems sharing files with NFS.  There the error was similar but very slightly different:
```
make[2]: Entering directory `/cloud/login/dwd/work/singularity/src'
gcc -DHAVE_CONFIG_H -I.  -DBINDIR=\"/usr/local/bin\" -DSYSCONFDIR=\"/usr/local/etc\" -DLOCALSTATEDIR=\"/usr/local/var\" -DLIBEXECDIR=\"/usr/local/libexec\" -DNS_CLONE_NEWPID -DNS_CLONE_FS -DNS_CLONE_NEWNS -DNS_CLONE_NEWUSER -DNS_CLONE_NEWIPC -DNS_CLONE_NEWNET -DSINGULARITY_NO_NEW_PRIVS -DSINGULARITY_MS_SLAVE  -Wall -fpie -fPIC -g -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -fstack-protector --param ssp-buffer-size=4 -MT docker_extract-docker-extract.o -MD -MP -MF .deps/docker_extract-docker-extract.Tpo -c -o docker_extract-docker-extract.o `test -f 'docker-extract.c' || echo './'`docker-extract.c
docker-extract.c:12:21: fatal error: archive.h: No such file or directory
 #include <archive.h>
                     ^
compilation terminated.
make[2]: *** [docker_extract-docker-extract.o] Error 1
make[2]: Leaving directory `/cloud/login/dwd/work/singularity/src'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/cloud/login/dwd/work/singularity/src'
make: *** [install-recursive] Error 1
```

So I think there's a problem with the docker-extract Makefile causing a rebuild when it shouldn't.

A workaround is to install libarchive-devel on the install machine.

**Comment by DrDaveD** [comment]
The very reason why it tries to recompile this program is because of the missing header file.  If I install libarchive-devel, it does not try to recompile.  So I think the only thing to do about this is to install libarchive-devel on the install machine.

**Comment by dtrudg** [comment]
Will close this as GodloveD has made the release of 2.4.4, and @moskalenko confirmed on slack this is OK r.e. the installation pattern raised in this issue.

Per release announcement, docker whiteout functionality will be added back in future release.
