### ISSUE TITLE
Build error: 'O_CLOEXEC' undeclared

### ISSUE THREAD

**Issue by robertdfrench** [apptainer/singularity#418]
Hello!

Very excited about this project. I am having a bit of trouble building the latest master. Building on SLES 11.3 with gcc 5.3.0 gives me this error  in sessiondir.c:

```
sessiondir.c: In function 'singularity_sessiondir_init':
sessiondir.c:92:45: error: 'O_CLOEXEC' undeclared (first use in this function)
     if ( ( sessiondir_fd = open(sessiondir, O_CLOEXEC | O_RDONLY) ) < 0 ) { // Flawfinder: ignore
```

Has anyone else bumped into this? I will try building on RHEL with a newer gcc and see if I can reproduce this there as well.

**Comment by robertdfrench** [comment]
Works fine on RHEL6 with gcc 6.2.0. I will dig some more to see what is going on with the SLES build. Perhaps O_CLOEXEC is defined elsewhere on older systems

**Comment by gmkurtzer** [comment]
What version of glibc does SLES11.3 include?

This is a recent change to the master and 2.x branch. Perhaps try the released version of 2.2?

**Comment by robertdfrench** [comment]
The 2.2 tag builds without issues on SLES 11.3, thank you. glibc version is 2.11.3, fwiw.

I'm good to go at this point, would you like me to close this issue?

**Comment by gmkurtzer** [comment]
Please leave this open, I will need to debug and get this working. Using the released 2.2 is just a temporary workaround. 

My guess is that SLES may need GNU_SOURCE defined or it is included in a different header. If it turns out it is unavailable, I may have to do something more drastic. In either case, I will probably ask you to test some things as I do not have a SLES build or test system. 

Thanks for pointing this out!

Greg

**Comment by bbockelm** [comment]
`O_CLOEXEC` is a bit of a newer flag (well, relatively - about 7 years old).  `FD_CLOEXEC` (as a flag to `fcntl`) dates back further.  Should be defined in `<fcntl.h>`; neither should require `GNU_SOURCE` to be set.

**Comment by gmkurtzer** [comment]
Hi @robertdfrench, can you please test the 2.x branch now?

Thank you!

**Comment by ak-80** [comment]
Hi, 

Still the same error on SLES 11.4 with glibc 2.11.3-17.102.1 compiling session_dir.c and loop-control.c from master branch. After changing O_CLOEXEC --> FD_CLOEXEC build process works fine.

**Comment by gmkurtzer** [comment]
Hi @ak-80.

Did you test FD_CLOEXEC via a call to `fcntl()` or did you replace it for O_CLOEXEC? If you replaced it in the call to `open()`, I don't think you will get the desired results (according to fcntl-linux.h I think it would be open as write only Vs. close on exec).

Can you and @robertdfrench test the 'development' branch against SLES 11.3? I want to make sure this bug is squashed in the latest development code before closing.

Thanks!

**Comment by ak-80** [comment]
Hi @gmkurtzer 

Compilation of the branch **2.x** works fine on SLES 11.4 with glibc 2.11.3-17.102.1. 

**development** branch still has same problems. 
...
sessiondir.c:   In function "singularity_sessionder_init":
sessiondir.c:92:  error: "O_CLOEXEC" undeclared (first use in this function)
...

**Comment by gmkurtzer** [comment]
@ak-80 I don't think you are using a current version of the development branch (e.g. the initialization function was renamed a while ago and is no longer suffixed with _init). Can you verify?

https://github.com/singularityware/singularity/blob/development/src/util/sessiondir.c

**Comment by ak-80** [comment]
@gmkurtzer 

You were right. Due to some unclear reason, I had very old (last commit on 19th of December 2016) version of development branch. After the update to the newest version, everything compiles fine. 

Thank you.

**Comment by vsoch** [comment]
Awesome! I'm going to close this issue, let us know if anything else buggy emerges!

**Comment by gmkurtzer** [comment]
Fantastic, thanks for letting us know @ak-80!

**Comment by gmkurtzer** [comment]
Hi all, I made change in https://github.com/singularityware/singularity/commit/4ce4fd38ba3d009bd17653005eb560159a204c41 that may affect this. Can you guys test the latest development branch where it was failing before due to `*_CLOEXEC` please?

Thanks!

**Comment by zyndagj** [comment]
This commit works with SLES 11.3 and glibc-2.11.3-17.90.4

**Comment by gmkurtzer** [comment]
Excellent, thank you!

**Comment by zyndagj** [comment]
Hello,

I previously reported that 4ce4fd38ba3d009bd17653005eb560159a204c41 correctly compiled on SLES 11.3 with glibc-2.11.3-17.90.4, but now it seems to be functioning incorrectly. I have been testing it today on CentOS Linux release 7.2.1511 with glibc-2.17-106 and it seems that users without unelevated privileges can create and modify images as I demonstrate with the `build` user below.

```
build@Wc253-101(20)$ singularity create --size 4000 tensorflow.img
Initializing Singularity image subsystem
Opening image file: tensorflow.img
Creating 4000MiB image
Binding image to loop
Creating file system within image
Image is done: tensorflow.img
build@Wc253-101(22)$ singularity import tensorflow.img docker://tensorflow/tensorflow:latest
Docker image path: index.docker.io/tensorflow/tensorflow:latest
Cache folder set to /admin/build/.singularity/docker
Downloading layer sha256:52e18a0f2ca741bb6d5123a2ab499d89206628a5b48a18bceaa04729ecf53908
Progress |========================================| 100.0% downloading layer
Progress |========================================| 100.0% preparing layer
Downloading layer sha256:cf26e7f79a1f56674084ecfde0f9cd5b21c495bcd1dacdf09e10af0518cfab47
Progress |========================================| 100.0% downloading layer
Progress |========================================| 100.0% preparing layer
Downloading layer sha256:f1d0b6192b60f1baa4d997e574632d8d5e5d0e6508a13dff58a1458162b0dfef
Progress |========================================| 100.0% downloading layer
Progress |========================================| 100.0% preparing layer
Downloading layer sha256:d3cca787fa7c8d05f2c94ece1eb7a6a6a86222c6b2fb73914154751947f708a7
Progress |========================================| 100.0% downloading layer
Progress |========================================| 100.0% preparing layer
Downloading layer sha256:24b58a5e905fd20ae2c7bb9c5d6391e51189d9a2ca1066eab30912734fda1324
Progress |========================================| 100.0% downloading layer
Progress |========================================| 100.0% preparing layer
Downloading layer sha256:4ed0083b781529482cdb00c17b7b91fb09770189eea88a5fac14f36fb6678993
Progress |========================================| 100.0% downloading layer
Progress |========================================| 100.0% preparing layer
Downloading layer sha256:f181e59dac0601bdc55f13bcfce844315f039c1dbc7dcd9ab27a1392df4b7a30
Progress |========================================| 100.0% downloading layer
Progress |========================================| 100.0% preparing layer
Importing: base Singularity environment
Importing: /admin/build/.singularity/docker/sha256:c62795f78da9ad31d9669cb4feb4e8fba995a299a0b2bd0f05b10fdc05b1f35e.tar.gz
Importing: /admin/build/.singularity/docker/sha256:d4fceeeb758e5103c39daf44c73404bf476ef6fd6b7a9a11e2260fcc1797c806.tar.gz
Importing: /admin/build/.singularity/docker/sha256:5c9125a401ae0cf5a5b4128633e7a4e84230d3eb4c541c661618a70e5d29aeff.tar.gz
Importing: /admin/build/.singularity/docker/sha256:0062f774e9942f61d13928855ab8111adc27def6f41bd6f7902c329ec836882b.tar.gz
Importing: /admin/build/.singularity/docker/sha256:6b33fd031facf4d7dd97afeea8a93260c2f15c3e795eeccd8969198a3d52678d.tar.gz
Importing: /admin/build/.singularity/docker/sha256:52e18a0f2ca741bb6d5123a2ab499d89206628a5b48a18bceaa04729ecf53908.tar.gz
Importing: /admin/build/.singularity/docker/sha256:cf26e7f79a1f56674084ecfde0f9cd5b21c495bcd1dacdf09e10af0518cfab47.tar.gz
Importing: /admin/build/.singularity/docker/sha256:f1d0b6192b60f1baa4d997e574632d8d5e5d0e6508a13dff58a1458162b0dfef.tar.gz
Importing: /admin/build/.singularity/docker/sha256:d3cca787fa7c8d05f2c94ece1eb7a6a6a86222c6b2fb73914154751947f708a7.tar.gz
Importing: /admin/build/.singularity/docker/sha256:24b58a5e905fd20ae2c7bb9c5d6391e51189d9a2ca1066eab30912734fda1324.tar.gz
Importing: /admin/build/.singularity/docker/sha256:4ed0083b781529482cdb00c17b7b91fb09770189eea88a5fac14f36fb6678993.tar.gz
Importing: /admin/build/.singularity/docker/sha256:f181e59dac0601bdc55f13bcfce844315f039c1dbc7dcd9ab27a1392df4b7a30.tar.gz
Importing: /admin/build/.singularity/metadata/sha256:2f36cb5b3330bf555e37df518f88bca1b0f272fb16f0763435ff259451dc67f9.tar.gz
build@Wc253-101(23)$ singularity shell tensorflow.img
Singularity: Invoking an interactive shell within container...
```
When the same commands were run using the 2.2.1 release 8755ff141d50bdaacd3dc53771f017b678475f73, I correctly received
```
build@Wc253-101(6)$ singularity create --size 4000 tensorflow.img
ERROR: Calling user must be root!
```

**Comment by gmkurtzer** [comment]
Heya @zyndagj, that is a feature! :)

Still requires root to bootstrap however.

**Comment by zyndagj** [comment]
Good to know. Thanks!
