### PR TITLE
Fix x86/arm/mips 32 bits system compilation error

### PR DESCRIPTION
**Pull request by cclerget**
## Description of the Pull Request (PR):

Fix regression introduced by #4742 causing compilation issue with x86/arm/mips 32 bits system.

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by dtrudg — APPROVED** [review]

**Comment by onlyjob** [comment]
Even with this commit I'm still getting the following FTBFS on _x86_32_:

```
# github.com/sylabs/singularity/pkg/util/fs/lock
../pkg/util/fs/lock/const_linux_32bit.go:13:2: setLk redeclared in this block
	previous declaration at ../pkg/util/fs/lock/const.go:13:10
```

Could you have a look please?

**Comment by cclerget** [comment]
@onlyjob Probably missed something about Go build constraint syntax. Will fix that

**Comment by onlyjob** [comment]
Looks good and the build succeeded on x86_32. Thanks!
